version: 2
jobs:
  build_and_push:
    docker:
      - image: docker:stable
    environment:
      COMPOSE_PROJECT_NAME: bec-alerts
    steps:
      - run:
          name: Install checkout deps
          command: |
            set -x
            apk update
            apk add git openssh

      - checkout
      - setup_remote_docker

      - run:
          name: Create version.json
          command: |
            # create a version.json per https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md
            printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" \
            "$CIRCLE_TAG" \
            "$CIRCLE_PROJECT_USERNAME" \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_BUILD_URL" > version.json

      - run:
          name: Build Docker image
          command: |
            docker info
            docker build -t ${CIRCLE_PROJECT_REPONAME}:build .

      - run:
          name: Install Docker Compose
          command: |
            set -x
            apk add --no-cache py-pip
            pip install docker-compose

      - run:
          name: Run tests
          command: |
            docker-compose up -d processor-postgres
            docker-compose up -d localstack
            docker run \
              --network bec-alerts_default \
              --link bec-alerts_processor-postgres \
              --link bec-alerts_localstack \
              --env-file ./docker/processor.env \
              --tty \
              --interactive \
              ${CIRCLE_PROJECT_REPONAME}:build pytest /app

      - run:
          name: Push to Dockerhub
          command: |
            function retry {
                set +e
                local n=0
                local max=3
                while true; do
                "$@" && break || {
                  if [[ $n -lt $max ]]; then
                    ((n++))
                    echo "Command failed. Attempt $n/$max:"
                  else
                    echo "Failed after $n attempts."
                    exit 1
                  fi
                }
                done
                set -e
            }

            export DOCKER_IMAGE="mozilla/${CIRCLE_PROJECT_REPONAME}:latest"
            if [ -n "${CIRCLE_TAG}" ]; then
                export DOCKER_IMAGE="mozilla/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}"
            fi

            if [ "${CIRCLE_BRANCH}" == "master" ] || [ -n "${CIRCLE_TAG}" ]; then
                echo "${DOCKER_PASSWORD}" | docker login -u="${DOCKER_USERNAME}" --password-stdin
                retry docker tag "${CIRCLE_PROJECT_REPONAME}:build" "${DOCKER_IMAGE}"
                retry docker push "${DOCKER_IMAGE}"
            fi

workflows:
  version: 2

  # workflow jobs are _not_ run in tag builds by default
  # we use filters to whitelist jobs that should be run for tags

  # workflow jobs are run in _all_ branch builds by default
  # we use filters to blacklist jobs that shouldn't be run for a branch

  # see: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution

  build_and_push:
    jobs:
      - build_and_push:
          filters:
            tags:
              only: /.*/
